### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by ccleve** [greenplum-db/postgres#27]
What's the status of this project? There hasn't been any activity for 10 months.

Is it dead? Is there a successor or similar project anywhere?

**Comment by danielgustafsson** [comment]
This is not an active repository, all work is now done on the upstream postgres repository.

**Comment by ccleve** [comment]
Thanks. I looked at the upstream repo here: https://github.com/postgres/postgres I don't see a src/backend/access/zedstore directory or a Zedstore branch or tag. A search for "columnar" didn't turn anything up. Can you point me to where the work on columnar storage is being done on the upstream repo? @danielgustafsson

**Comment by danielgustafsson** [comment]
It's being discussed on the upstream PostgreSQL mailing lists at: 

https://www.postgresql.org/message-id/flat/CAE-ML%2B-HwY4X4uTzBesLhOotHF7rUvP2Ur-rvEpqz2PUgK4K3g%40mail.gmail.com#1b4ae5289ad9666e603049c98a3f0141

This is the main thread, and there are a few auxiliary ones for work on related table access management parts. The thread has stalled now as there is little active work going on, so if you're interested in this I would recommend replying to that thread and inquiring about status.
